# Generated by Django 2.1.7 on 2020-08-22 00:16

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
                ('is_delete', models.BooleanField(default=False, verbose_name='DeleteFlag')),
                ('name', models.CharField(max_length=20, verbose_name='GoodsSPUName')),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='GoodsDescription')),
            ],
            options={
                'verbose_name': 'GoodsSPU',
                'verbose_name_plural': 'GoodsSPU',
                'db_table': 'df_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
                ('is_delete', models.BooleanField(default=False, verbose_name='DeleteFlag')),
                ('image', models.ImageField(upload_to='goods', verbose_name='ImagePath')),
            ],
            options={
                'verbose_name': 'GoodsImage',
                'verbose_name_plural': 'GoodsImage',
                'db_table': 'df_goods_image',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
                ('is_delete', models.BooleanField(default=False, verbose_name='DeleteFlag')),
                ('name', models.CharField(max_length=20, verbose_name='GoodsName')),
                ('desc', models.CharField(max_length=256, verbose_name='GoodsDescription')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('unite', models.CharField(max_length=20, verbose_name='Units')),
                ('stock', models.IntegerField(default=1, verbose_name='Stocks')),
                ('image', models.ImageField(upload_to='goods', verbose_name='Images')),
                ('status', models.SmallIntegerField(choices=[(0, 'OnSale'), (1, 'OffSale')], default=1, verbose_name='Status')),
                ('sales', models.IntegerField(default=0, verbose_name='Sales')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='GoodsSPU')),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
                'db_table': 'df_goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
                ('is_delete', models.BooleanField(default=False, verbose_name='DeleteFlag')),
                ('name', models.CharField(max_length=20, verbose_name='TypeName')),
                ('logo', models.CharField(max_length=20, verbose_name='Logo')),
                ('image', models.ImageField(upload_to='type', verbose_name='TypeImage')),
            ],
            options={
                'verbose_name': 'GoodsType',
                'verbose_name_plural': 'GoodsType',
                'db_table': 'df_goods_type',
            },
        ),
        migrations.CreateModel(
            name='IndexGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
                ('is_delete', models.BooleanField(default=False, verbose_name='DeleteFlag')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Image')),
                ('index', models.SmallIntegerField(default=0, verbose_name='DisplayOrder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU', verbose_name='GoodsSKU')),
            ],
            options={
                'verbose_name': 'HomepageCarouselGoods',
                'verbose_name_plural': 'HomepageCarouselGoods',
                'db_table': 'df_index_banner',
            },
        ),
        migrations.CreateModel(
            name='IndexPromotionBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
                ('is_delete', models.BooleanField(default=False, verbose_name='DeleteFlag')),
                ('name', models.CharField(max_length=20, verbose_name='ActivityName')),
                ('url', models.URLField(verbose_name='ActivityURL')),
                ('image', models.ImageField(upload_to='banner', verbose_name='ActivityImage')),
                ('index', models.SmallIntegerField(default=0, verbose_name='DisplayOrder')),
            ],
            options={
                'verbose_name': 'HomepagePromotionActivity',
                'verbose_name_plural': 'HomepagePromotionActivity',
                'db_table': 'df_index_promotion',
            },
        ),
        migrations.CreateModel(
            name='IndexTypeGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
                ('is_delete', models.BooleanField(default=False, verbose_name='DeleteFlag')),
                ('display_type', models.SmallIntegerField(choices=[(0, 'Title'), (1, 'Image')], default=1, verbose_name='DisplayType')),
                ('index', models.SmallIntegerField(default=1, verbose_name='DisplayOrder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU', verbose_name='GoodsSKU')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType', verbose_name='GoodsType')),
            ],
            options={
                'verbose_name': 'HomePageTypeGoodsDisplay',
                'verbose_name_plural': 'HomePageTypeGoodsDisplay',
                'db_table': 'df_index_type_goods',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType', verbose_name='GoodsType'),
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU', verbose_name='GoodsSKU'),
        ),
    ]
