# Generated by Django 2.1.7 on 2020-08-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
                ('is_delete', models.BooleanField(default=False, verbose_name='DeleteFlag')),
                ('count', models.IntegerField(default=1, verbose_name='GoodsCount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('comment', models.CharField(default='', max_length=256, verbose_name='Review')),
            ],
            options={
                'verbose_name': 'OrderGoods',
                'verbose_name_plural': 'OrderGoods',
                'db_table': 'df_order_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
                ('is_delete', models.BooleanField(default=False, verbose_name='DeleteFlag')),
                ('order_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='OrderID')),
                ('pay_method', models.SmallIntegerField(choices=[(1, 'Pay On Delivery'), (2, 'Pay By Wechat'), (3, 'Pay By AliPay'), (4, 'Pay by UnionPay')], default=3, verbose_name='PayMethod')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('total_count', models.IntegerField(default=1, verbose_name='TotalCount')),
                ('transit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TransmitFee')),
                ('order_status', models.SmallIntegerField(choices=[(1, 'Unpaid'), (2, 'BackOrder'), (3, 'Unreceived'), (4, 'Unreviewed'), (5, 'Completed')], default=1, verbose_name='OrderStatus')),
                ('trade_no', models.CharField(default='', max_length=128, verbose_name='TradeNumber')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
                'db_table': 'df_order_info',
            },
        ),
    ]
